### PR TITLE
Update SwiftRazorpayPlugin.swift

### PR DESCRIPTION
**Pull request by sharad-paghadal**
Added support to add notes.

### CODE REVIEW

**Comment by dynamitechetan** [comment]
Hi @sharad-paghadal.. Thanks for the contribution.. Have you tested it out... I mean is it coming on the razorpay dashboard. Can I test it on a simulator?

**Comment by sharad-paghadal** [comment]
Yes it's working properly, and I'm using the same code for my app. notes are showing in razorpay dashboard as well as comes in razorpay webhook.

**Comment by rajeevjaiswal** [comment]
@sharad-paghadal does this solve swift 5 build issue?

**Comment by sharad-paghadal** [comment]
No

**Pull request merged**
